### ISSUE TITLE
[c++] Nightly build failure on `formattable` of `json` type

### ISSUE THREAD

**Issue by jdblischak** [single-cell-data/TileDB-SOMA#2608]
The linux-64 nightly tiledbsoma-feedstock builds are currently passing with fmt9 but failing with fmt10. Here is the error message (I replaced the long path to the conda host env with `${HOST_ENV}`):

```sh
[ 65%] Building CXX object src/CMakeFiles/TILEDB_SOMA_OBJECTS.dir/utils/arrow_adapter.cc.o
In file included from ${HOST_ENV}/include/spdlog/fmt/fmt.h:32,
                 from ${HOST_ENV}/include/spdlog/common.h:50,
                 from ${HOST_ENV}/include/spdlog/spdlog.h:12,
                 from /home/conda/feedstock_root/build_artifacts/tiledbsoma_1716169644869/work/libtiledbsoma/src/utils/../utils/logger.h:54,
                 from /home/conda/feedstock_root/build_artifacts/tiledbsoma_1716169644869/work/libtiledbsoma/src/utils/arrow_adapter.cc:35:
${HOST_ENV}/include/fmt/core.h: In instantiation of 'constexpr fmt::v10::detail::value<Context> fmt::v10::detail::make_arg(T&) [with bool PACKED = true; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; T = nlohmann::basic_json<>; typename std::enable_if<PACKED, int>::type <anonymous> = 0]':
${HOST_ENV}/include/fmt/core.h:1842:51:   required from 'constexpr fmt::v10::format_arg_store<Context, Args>::format_arg_store(T& ...) [with T = {nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >}; Context = fmt::v10::basic_format_context<fmt::v10::appender, char>; Args = {nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >}]'
${HOST_ENV}/include/fmt/core.h:1860:18:   required from 'constexpr fmt::v10::format_arg_store<Context, typename std::remove_cv<typename std::remove_reference<T>::type>::type ...> fmt::v10::make_format_args(T& ...) [with Context = basic_format_context<appender, char>; T = {nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >}]'
${HOST_ENV}/include/fmt/core.h:2835:44:   required from 'std::string fmt::v10::format(format_string<T ...>, T&& ...) [with T = {nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >&}; std::string = std::__cxx11::basic_string<char>; format_string<T ...> = basic_format_string<char, nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > >&>]'
/home/conda/feedstock_root/build_artifacts/tiledbsoma_1716169644869/work/libtiledbsoma/src/utils/arrow_adapter.cc:342:24:   required from here
${HOST_ENV}/include/fmt/core.h:1600:63: error: 'fmt::v10::detail::type_is_unformattable_for<nlohmann::basic_json<>, char> _' has incomplete type
 1600 |     type_is_unformattable_for<T, typename Context::char_type> _;
      |                                                               ^
${HOST_ENV}/include/fmt/core.h:1604:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
 1604 |       formattable,
      |       ^~~~~~~~~~~
${HOST_ENV}/include/fmt/core.h:1604:7: note: 'formattable' evaluates to false
[ 69%] Building CXX object src/CMakeFiles/TILEDB_SOMA_OBJECTS.dir/utils/logger.cc.o
make[5]: *** [src/CMakeFiles/TILEDB_SOMA_OBJECTS.dir/build.make:272: src/CMakeFiles/TILEDB_SOMA_OBJECTS.dir/utils/arrow_adapter.cc.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [CMakeFiles/Makefile2:100: src/CMakeFiles/TILEDB_SOMA_OBJECTS.dir/all] Error 2
make[3]: *** [Makefile:136: all] Error 2
make[2]: *** [CMakeFiles/libtiledbsoma.dir/build.make:86: libtiledbsoma-prefix/src/libtiledbsoma-stamp/libtiledbsoma-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/libtiledbsoma.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

I think this new error was introduced in https://github.com/single-cell-data/TileDB-SOMA/pull/2541. I have two main reasons:

* The error is about `nlohmann::basic_json`, and `nlohmann/json.hpp` was added in that PR
* The last passing nightly libtiledbsoma build was on [May 16th](https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=39552&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7), and it used commit bcfa0604d89d9739547339102077529b16638b55. The first failing libtiledbsoma build was on [May 17th](     https://dev.azure.com/TileDB-Inc/CI/_build/results?buildId=39559&view=logs&j=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e&t=6d4b912b-175d-51da-0fd9-4d30fe1eb4e7), and it used commit 12566ddd82b23cb3ab978af70b1f2a40d3592084. Comparing these two commits, https://github.com/single-cell-data/TileDB-SOMA/compare/bcfa0604d89d9739547339102077529b16638b55...12566ddd82b23cb3ab978af70b1f2a40d3592084, there was only one PR that affected the C++ code

xref: https://github.com/TileDB-Inc/tiledbsoma-feedstock/issues/153#issuecomment-2120605388

**Comment by jdblischak** [comment]
Fixed by @johnkerl in https://github.com/single-cell-data/TileDB-SOMA/pull/2609 :tada:
